# Generated by Django 2.2.1 on 2019-07-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190724_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
