# Generated by Django 2.2.1 on 2019-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='my_in',
            field=models.SmallIntegerField(db_column='in', default=0, verbose_name='incoming'),
        ),
        migrations.AlterField(
            model_name='message',
            name='next_command',
            field=models.CharField(max_length=255, verbose_name='next_command'),
        ),
        migrations.AlterField(
            model_name='message',
            name='previous_command',
            field=models.CharField(max_length=255, verbose_name='prev_command'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
    ]
