# Generated by Django 2.2.1 on 2019-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190725_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='next_command',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='next_command'),
        ),
        migrations.AlterField(
            model_name='message',
            name='previous_command',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='prev_command'),
        ),
    ]
