# Generated by Django 2.2.1 on 2019-07-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('text', models.TextField(default='')),
                ('previous_command', models.CharField(max_length=255)),
                ('next_command', models.CharField(max_length=255)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Chat')),
            ],
        ),
    ]
