# Generated by Django 2.2.1 on 2019-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='my_in',
            field=models.SmallIntegerField(db_column='in', default=0),
        ),
    ]
